
out_dir: data/models/prova2/
model_params:
  arch: resnet50 # model architecture from torchvision namespace
  weights: null # null -> all models are initialized with "ImageNet" weights or path to .ckpt to initialize from pre-trained model
  batch_size: 32
  val_check_interval: 0.5 # validate after each half epoch
  optim:
    # SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    # MultiStepLR
    params:
      gamma: 0.5
      milestones: [1]
  partitionings:
    ptype: default
    shortnames: [coarse, middle, fine]
    files:
      - resources/s2_cells/cells_50_5000.csv
      - resources/s2_cells/cells_50_2000.csv
      - resources/s2_cells/cells_50_1000.csv
  # images stored in chunks
  msgpack_train_dir: resources/images/im2gps
  msgpack_val_dir: resources/images/im2gps
  # meta information i.e. coordinates for each image
  train_meta_path: resources/im2gps_places365.csv
  val_meta_path: resources/im2gps_places365.csv
  # mapping from image ids in msgpack dataset to target value(s)
  # orient: index -> {"img_id": [t1, t2], ...}
  train_label_mapping: resources/im2gps_places365_mapping_h3.json
  val_label_mapping: resources/im2gps_places365_mapping_h3.json
  num_workers_per_loader: 4
# paramters for pytorch lightning trainer class
trainer_params:
  #gpus: 1
  max_epochs: 2
  distributed_backend: 'ddp_cpu'
  #distributed_backend: null
  precision: 16
  reload_dataloaders_every_epoch: true # necessary to shuffle IterableDataset
